// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleServiceManagement.API.Data;

#nullable disable

namespace VehicleServiceManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102214931_AddFuelTypeToVehicle")]
    partial class AddFuelTypeToVehicle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PartsCharge")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ServiceCharge")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BillId");

                    b.HasIndex("BillNumber")
                        .IsUnique();

                    b.HasIndex("ServiceRequestId")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PartId");

                    b.HasIndex("PartName")
                        .IsUnique();

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            Description = "Synthetic engine oil 5W-30, 5 quarts",
                            PartName = "Engine Oil 5W-30",
                            PartNumber = "OIL-5W30-001",
                            QuantityInStock = 50,
                            ReorderLevel = 10,
                            Supplier = "AutoParts Inc.",
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            PartId = 2,
                            Description = "Premium oil filter",
                            PartName = "Oil Filter",
                            PartNumber = "FILTER-OIL-002",
                            QuantityInStock = 100,
                            ReorderLevel = 20,
                            Supplier = "AutoParts Inc.",
                            UnitPrice = 8.00m
                        },
                        new
                        {
                            PartId = 3,
                            Description = "Engine air filter",
                            PartName = "Air Filter",
                            PartNumber = "FILTER-AIR-003",
                            QuantityInStock = 75,
                            ReorderLevel = 15,
                            Supplier = "FilterPro",
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            PartId = 4,
                            Description = "Ceramic brake pads for front wheels",
                            PartName = "Brake Pads (Front)",
                            PartNumber = "BRAKE-PAD-F-004",
                            QuantityInStock = 40,
                            ReorderLevel = 10,
                            Supplier = "BrakeMaster",
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            PartId = 5,
                            Description = "Ceramic brake pads for rear wheels",
                            PartName = "Brake Pads (Rear)",
                            PartNumber = "BRAKE-PAD-R-005",
                            QuantityInStock = 40,
                            ReorderLevel = 10,
                            Supplier = "BrakeMaster",
                            UnitPrice = 40.00m
                        },
                        new
                        {
                            PartId = 6,
                            Description = "Front brake rotor",
                            PartName = "Brake Rotor",
                            PartNumber = "BRAKE-ROTOR-006",
                            QuantityInStock = 30,
                            ReorderLevel = 8,
                            Supplier = "BrakeMaster",
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            PartId = 7,
                            Description = "12V automotive battery, 600 CCA",
                            PartName = "Car Battery 12V",
                            PartNumber = "BATTERY-12V-007",
                            QuantityInStock = 25,
                            ReorderLevel = 5,
                            Supplier = "PowerCell",
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            PartId = 8,
                            Description = "Engine coolant, 1 gallon",
                            PartName = "Coolant/Antifreeze",
                            PartNumber = "COOLANT-008",
                            QuantityInStock = 60,
                            ReorderLevel = 15,
                            Supplier = "AutoParts Inc.",
                            UnitPrice = 18.00m
                        },
                        new
                        {
                            PartId = 9,
                            Description = "Automatic transmission fluid, 1 quart",
                            PartName = "Transmission Fluid",
                            PartNumber = "TRANS-FLUID-009",
                            QuantityInStock = 80,
                            ReorderLevel = 20,
                            Supplier = "AutoParts Inc.",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            PartId = 10,
                            Description = "Transmission filter kit",
                            PartName = "Transmission Filter",
                            PartNumber = "TRANS-FILTER-010",
                            QuantityInStock = 35,
                            ReorderLevel = 10,
                            Supplier = "FilterPro",
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            PartId = 11,
                            Description = "R-134a refrigerant, 12 oz",
                            PartName = "AC Refrigerant",
                            PartNumber = "AC-REF-011",
                            QuantityInStock = 50,
                            ReorderLevel = 15,
                            Supplier = "ClimateControl",
                            UnitPrice = 22.00m
                        },
                        new
                        {
                            PartId = 12,
                            Description = "HEPA cabin air filter",
                            PartName = "Cabin Air Filter",
                            PartNumber = "FILTER-CABIN-012",
                            QuantityInStock = 60,
                            ReorderLevel = 12,
                            Supplier = "FilterPro",
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            PartId = 13,
                            Description = "Iridium spark plugs",
                            PartName = "Spark Plugs (Set of 4)",
                            PartNumber = "SPARK-PLUG-013",
                            QuantityInStock = 45,
                            ReorderLevel = 10,
                            Supplier = "AutoParts Inc.",
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            PartId = 14,
                            Description = "Engine serpentine belt",
                            PartName = "Serpentine Belt",
                            PartNumber = "BELT-SERP-014",
                            QuantityInStock = 40,
                            ReorderLevel = 10,
                            Supplier = "AutoParts Inc.",
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            PartId = 15,
                            Description = "Engine timing belt",
                            PartName = "Timing Belt",
                            PartNumber = "BELT-TIME-015",
                            QuantityInStock = 20,
                            ReorderLevel = 5,
                            Supplier = "AutoParts Inc.",
                            UnitPrice = 55.00m
                        });
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ServiceRequestId")
                        .IsUnique();

                    b.HasIndex("TechnicianId");

                    b.ToTable("ServiceAssignments");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            BasePrice = 50.00m,
                            CategoryName = "Oil Change",
                            Description = "Regular oil and filter change service",
                            EstimatedDurationMinutes = 30,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            BasePrice = 150.00m,
                            CategoryName = "Brake Service",
                            Description = "Complete brake pad replacement and inspection",
                            EstimatedDurationMinutes = 90,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            BasePrice = 40.00m,
                            CategoryName = "Tire Rotation",
                            Description = "Rotate and balance all four tires",
                            EstimatedDurationMinutes = 45,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            BasePrice = 100.00m,
                            CategoryName = "Engine Diagnostics",
                            Description = "Complete engine diagnostic scan and report",
                            EstimatedDurationMinutes = 60,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            BasePrice = 120.00m,
                            CategoryName = "AC Service",
                            Description = "Air conditioning system service and repair",
                            EstimatedDurationMinutes = 75,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            BasePrice = 180.00m,
                            CategoryName = "Transmission Service",
                            Description = "Transmission fluid change and inspection",
                            EstimatedDurationMinutes = 120,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 7,
                            BasePrice = 80.00m,
                            CategoryName = "Battery Replacement",
                            Description = "Battery testing and replacement",
                            EstimatedDurationMinutes = 30,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 8,
                            BasePrice = 90.00m,
                            CategoryName = "Wheel Alignment",
                            Description = "Four-wheel alignment service",
                            EstimatedDurationMinutes = 60,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 9,
                            BasePrice = 60.00m,
                            CategoryName = "General Inspection",
                            Description = "Comprehensive vehicle inspection",
                            EstimatedDurationMinutes = 45,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 10,
                            BasePrice = 70.00m,
                            CategoryName = "Coolant Flush",
                            Description = "Engine coolant system flush and refill",
                            EstimatedDurationMinutes = 45,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceChangeHistories");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServicePart", b =>
                {
                    b.Property<int>("ServicePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicePartId"));

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ServicePartId");

                    b.HasIndex("PartId");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("ServiceParts");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceRequest", b =>
                {
                    b.Property<int>("ServiceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceRequestId"));

                    b.Property<decimal>("ActualCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TechnicianRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ServiceRequestId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@vehicleservice.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$N8Nxpa0OwlDQOH1o5fG4AeIk5bj2BnKLevQXt4rvE.ZNsISwUV4m.",
                            PhoneNumber = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@vehicleservice.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Manager",
                            PasswordHash = "$2a$11$QvwLnXipT4YVfmzz.Q5Gde0R4T6SgGpfkT5LirH/lqdkWn4zbw8F6",
                            PhoneNumber = "1234567891",
                            Role = "ServiceManager"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mike.tech@vehicleservice.com",
                            FirstName = "Mike",
                            IsActive = true,
                            LastName = "Tech",
                            PasswordHash = "$2a$11$mnTwMhrbVbEpwZpxGgPYGOmRtR1OGwXXCyzrcimE6X6AziykpHyAu",
                            PhoneNumber = "1234567892",
                            Role = "Technician"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.mechanic@vehicleservice.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Mechanic",
                            PasswordHash = "$2a$11$Apcr/s8uYl02tv2BxjDGf.UtlOKIS.riZsdJvLX0/wun/K2drVhiW",
                            PhoneNumber = "1234567893",
                            Role = "Technician"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.customer@email.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "$2a$11$jh4lz5QMA2Dg21QHfp5oTeHYPA4qvZq9eMqrO3lHl2Jy6VTrrhJNS",
                            PhoneNumber = "1234567894",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Bill", b =>
                {
                    b.HasOne("VehicleServiceManagement.API.Models.ServiceRequest", "ServiceRequest")
                        .WithOne("Bill")
                        .HasForeignKey("VehicleServiceManagement.API.Models.Bill", "ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Payment", b =>
                {
                    b.HasOne("VehicleServiceManagement.API.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceAssignment", b =>
                {
                    b.HasOne("VehicleServiceManagement.API.Models.ServiceRequest", "ServiceRequest")
                        .WithOne("ServiceAssignment")
                        .HasForeignKey("VehicleServiceManagement.API.Models.ServiceAssignment", "ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleServiceManagement.API.Models.User", "Technician")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServicePart", b =>
                {
                    b.HasOne("VehicleServiceManagement.API.Models.Part", "Part")
                        .WithMany("ServiceParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleServiceManagement.API.Models.ServiceRequest", "ServiceRequest")
                        .WithMany("ServiceParts")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceRequest", b =>
                {
                    b.HasOne("VehicleServiceManagement.API.Models.ServiceCategory", "Category")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleServiceManagement.API.Models.User", "Customer")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleServiceManagement.API.Models.Vehicle", "Vehicle")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleServiceManagement.API.Models.User", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Part", b =>
                {
                    b.Navigation("ServiceParts");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceCategory", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.ServiceRequest", b =>
                {
                    b.Navigation("Bill");

                    b.Navigation("ServiceAssignment");

                    b.Navigation("ServiceParts");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.User", b =>
                {
                    b.Navigation("ServiceAssignments");

                    b.Navigation("ServiceRequests");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleServiceManagement.API.Models.Vehicle", b =>
                {
                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
